### PR TITLE
PDF417: Check that input is made of 0...127 chars when using Compaction.TEXT, throw an explicit exception if not the case

### LINKED ISSUE #1761: pdf417 encode error java.lang.ArrayIndexOutOfBoundsException when using CHARACTER_SET ISO-8859-15
Hello,

I encountered an error while attempting to create a PDF417 barcode with character set ISO-8859-15. Here's the relevant code snippet:
```java
String content = "€ 123,45";

Map<EncodeHintType, Object> hints = new HashMap<>();
hints.put(EncodeHintType.ERROR_CORRECTION, 4);
hints.put(EncodeHintType.PDF417_DIMENSIONS, new com.google.zxing.pdf417.encoder.Dimensions(7, 7, 1, 300));
hints.put(EncodeHintType.MARGIN, 0);
hints.put(EncodeHintType.CHARACTER_SET, "ISO-8859-15");
hints.put(EncodeHintType.PDF417_COMPACTION, com.google.zxing.pdf417.encoder.Compaction.TEXT);

MultiFormatWriter writer = new MultiFormatWriter();
BitMatrix bitMatrix = writer.encode(content, BarcodeFormat.PDF_417, 200, 100, hints);
```

The error message I received is as follows:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 8364 out of bounds for length 128
        at com.google.zxing.pdf417.encoder.PDF417HighLevelEncoder.isMixed(PDF417HighLevelEncoder.java:557)
        at com.google.zxing.pdf417.encoder.PDF417HighLevelEncoder.encodeText(PDF417HighLevelEncoder.java:325)
        at com.google.zxing.pdf417.encoder.PDF417HighLevelEncoder.encodeHighLevel(PDF417HighLevelEncoder.java:212)
        at com.google.zxing.pdf417.encoder.PDF417.generateBarcodeLogic(PDF417.java:659)
        at com.google.zxing.pdf417.PDF417Writer.bitMatrixFromEncoder(PDF417Writer.java:111)
        at com.google.zxing.pdf417.PDF417Writer.encode(PDF417Writer.java:90)
        at com.google.zxing.MultiFormatWriter.encode(MultiFormatWriter.java:102)
        at barcode.BarcodeGenerator.generate(BarcodeGenerator.java:48)
        at test.test.main(test.java:11)
```

thank you

### PR DESCRIPTION
**Pull request by ftiercelin**
- [x] when encoding a PDF417 with TEXT compaction, check if input is made of chars in the 0...127 range
- [x] if not, throw an exception recommending the use of AUTO compaction instead
- [x] add UT to test the above changes

Fixes #1761

### CODE REVIEW

File: core/src/main/java/com/google/zxing/pdf417/encoder/PDF417HighLevelEncoder.java [hunk 1]
```diff
@@ -174,16 +174,15 @@ static String encodeHighLevel(String msg, Compaction compaction, Charset encodin
     if (msg.isEmpty()) {
       throw new WriterException("Empty message not allowed");
     }
+    
+    if (Compaction.TEXT == compaction) {
+      checkCharset(msg,127,"Consider specifying Compaction.AUTO instead of Compaction.TEXT");
```
Comment (srowen) [inline core/src/main/java/com/google/zxing/pdf417/encoder/PDF417HighLevelEncoder.java:179]: The logic looks OK; minor request though: everywhere in the change, follow a comma with a space for consistency

File: core/src/test/java/com/google/zxing/pdf417/encoder/PDF417EncoderTestCase.java [hunk 2]
```diff
@@ -27,19 +35,97 @@
  * Tests {@link PDF417HighLevelEncoder}.
  */
 public final class PDF417EncoderTestCase extends Assert {
-
+  private static final String PDF417PFX = "\u039f\u001A\u0385";
```
Comment (srowen) [inline core/src/test/java/com/google/zxing/pdf417/encoder/PDF417EncoderTestCase.java:38]: Nit: blank lines around this

**Review by srowen — CHANGES_REQUESTED** [review]

File: core/src/test/java/com/google/zxing/pdf417/encoder/PDF417EncoderTestCase.java (hunk 2 above)
Comment (ftiercelin) [reply core/src/test/java/com/google/zxing/pdf417/encoder/PDF417EncoderTestCase.java:39]: should be good now

**Review by srowen — APPROVED** [review]
